filter:
    excluded_paths: [doc/*]

checks:
    php: true

tools:
    php_code_sniffer:
        config:
            standard: 'PSR2'

build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
